### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by GoldSubmarine** [cortinico/ktfmt-gradle#10]
## 🐛 Describe the bug
I'm Chinese, so there will be some Chinese comments in the code. The original encoding format was UTF8, but after format it changed to GBK(a coding format issued by the Chinese government). By the way ,when I installed Windows 10, the language I chose was Chinese, so the system default code is GBK.

To solve the problem, I have configured Gradle as follows:

```
// build.gradle.kts
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
```

```
// gradle.properties
systemProp.file.encoding=UTF-8
```

But it didn't work.

## 💣 Steps to reproduce

I've just typed a few Chinese characters, maybe you can copy them into the test code and see if you can reproduce them.

I guess it's hard to reproduce because your operating system is not Chinese.

主键

## 📷 Screenshots

before:

![image](https://user-images.githubusercontent.com/22909744/108841784-45a79980-7613-11eb-85ba-639f260da4ac.png)

after:

![image](https://user-images.githubusercontent.com/22909744/108841739-34f72380-7613-11eb-9cc2-037e7d5ff8bd.png)

## 📱 Tech info
 - Device: dell pc
 - OS: windows10
 - Library/App version: 0.2.0

**Comment by cortinico** [comment]
> I guess it's hard to reproduce because your operating system is not Chinese.

Exactly. I've tried with the code you suggested and it reformats correctly for me, while still keeping the characters.

> The original encoding format was UTF8, but after format it changed to GBK(a coding format issued by the Chinese government). By the way ,when I installed Windows 10, the language I chose was Chinese, so the system default code is GBK.

I haven't fully understood what is happening here. Specifically as `UFT8` is a charset and `GBK` is an encoding. 

Are you suggesting that the tool changed the encoding of your source file?

**Comment by GoldSubmarine** [comment]
Sorry for the wrong description. `UTF8` and `GBK` are all charset. The file charset is changed from `utf8` to `GBK` after format. I want to keep the charset as UTF8. Did I describe it clearly? Forgive my poor English.

**Comment by GoldSubmarine** [comment]
I solved the problem by referring to this [Show UTF-8 text properly in Gradle](https://stackoverflow.com/questions/21267234/show-utf-8-text-properly-in-gradle)

But I don't know why my gradle configuration above does not work. 

I finally solved the problem with the following configuration:
```
// gradle.properties
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
```

**Comment by cortinico** [comment]
Great thanks for sharing your solution 👍
