### ISSUE TITLE
Support specified files at the command line

### ISSUE THREAD

**Issue by GoldSubmarine** [cortinico/ktfmt-gradle#12]
## 💡 Describe the solution you'd like

`java -jar /path/to/ktfmt-<VERSION>-jar-with-dependencies.jar [--dropbox-style] [files...]`

Ktfmt supports specifying files that need to be formatted. I want this feature when I use the command line, maybe it is:

`gradlew ktfmtFormat -Dglob=[files...]`

My actual usage scenarios is that I have changed five files, and want to commit two of them. I registered a git hook to format the file to be committed. So I just want to format two files.

You can reference this issue: [How to setup spotless for a git pre commit hook that only check changed files](https://github.com/diffplug/spotless/issues/178)

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
This doesn't work out of the box, mostly because Gradle doesn't have notion of Git and the whole idea behind the tool is to give you tasks that run autoformats for every source sets you have.

I have two questions to challenge this:

1. Why don't you use `ktfmt` directly from the pre-commit hook? If you have `gradlew ktfmtFormat` in a pre-commit hook you'll end up paying the configuration time for your Gradle build, making the pre-commit way slower.

2. Have you considered using one of the script from the issue you linked ([like this one](https://github.com/diffplug/spotless/issues/178#issuecomment-351638034))? Ktfmt-gradle has the concept of UP-TO-DATE files so it will only reformat the files that are actually modified.

**Comment by GoldSubmarine** [comment]
> This doesn't work out of the box, mostly because Gradle doesn't have notion of Git

I just want the ability to specify files in the command line. I'll use `git diff` to concatenate a file path string in the bash and then takes the string as a command-line argument. So it does not require a Git environment. 

> Why don't you use ktfmt directly from the pre-commit hook? If you have gradlew ktfmtFormat in a pre-commit hook you'll end up paying the configuration time for your Gradle build, making the pre-commit way slower.

I didn't want to use the `ktfmt.jar` directly, but instead introduced it as a plug-in so that it would be easy to upgrade the plug-in later. I think it's fast when I use the `--daemon` argument. And this is a common usage in frontend(Web), just like this popular project [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)
https://github.com/PanJiaChen/vue-element-admin/blob/33a93a12b4dc6429dbe91f43ef17fb76236f2d6c/package.json#L96-L106
It automatically registers a Git Hook by using [husky](https://github.com/typicode/husky) and use [lint-staged](https://github.com/okonet/lint-staged#why) to filter out the files to be committed, as it mentions in the README: Ultimately you only want to lint files that will be committed. 

> Have you considered using one of the script from the issue you linked?

Yes, I've already tried, ktfmt-gradle didn't work. What I want to achieve is to automatically format the committed files, so as I said above, the other three files don't need to be formatted. I'm a Web developer, and since this approach is widely used in the Web space, so I mention this feature request.

**Comment by GoldSubmarine** [comment]
Here is an other example from Facebook's formatting tool [prettier](https://prettier.io/docs/en/precommit.html)

**Comment by cortinico** [comment]
I see your point. So I'm thinking about an approach that could look like:

```
tasks.register<KtfmtFormatTask>("ktfmtPrecommit") {
    setSource(project.files(project.findProperty("glob").toString().split(":").toTypedArray()))
}
```

You would then call it with:

```
gw ktfmtPrecommit -Pglob=/opt/file1.kt:/opt/file2.kt
```

There are a couple of changes needed to make this possible.

**Comment by GoldSubmarine** [comment]
I understand your intention to customize to achieve flexibility or generality,but I doubt whether to do this, based on the following two reasons:

1. This plugin is a package of ktfmt, so this itself is one of the functions of ktfmt, and the functions of ktfmt are very limited, so is there really a need for customization?
2. Do you have a plan to be compatible with maven, or maybe someone else will submit a PR to be compatible with maven, using too many gradle features will make compatibility difficult.

So maybe a fixed api would be better, but this is just an immature suggestion, I don’t know much about gradle and maven.

**Comment by cortinico** [comment]
> This plugin is a package of ktfmt, so this itself is one of the functions of ktfmt, and the functions of ktfmt are very limited, so is there really a need for customization?

The rationale behind my suggestion is that I expose the `Tasks` classes that can be used externally to make custom `ktfmt` tasks if needed. So that's definitely aligned with the Gradle API and I believe that should be supported to some extent

> Do you have a plan to be compatible with maven, or maybe someone else will submit a PR to be compatible with maven, using too many gradle features will make compatibility difficult.

No plan to make this work with Maven, at least from my side

**Comment by GoldSubmarine** [comment]
If just support Gradle, this is a great solution.

**Comment by cortinico** [comment]
I've done some work on this front but with not much success. Currently Gradle expects that the `source` of a SourceTask is a directory, that doesn't play well with our use case of being a list of files.

See: https://github.com/gradle/gradle/issues/15679

**Comment by GoldSubmarine** [comment]
Yes, It seems that it can only do by include api

```
setSource(
    srcDir(project.rootDir).include(project.findProperty("glob").split(":"))
)
```

**Comment by cortinico** [comment]
> Yes, It seems that it can only do by include api

I'm unsure I follow you. Your script does not compile for me:

```
* What went wrong:
Script compilation errors:

  Line 26:         srcDir(project.rootDir).include(project.findProperty("glob").split(":"))
                   ^ Unresolved reference: srcDir
```

**Comment by GoldSubmarine** [comment]
I got it wrong. Forget it

**Comment by GoldSubmarine** [comment]
```bash
#!/bin/sh
# git config core.hooksPath hooks
echo '[git hook] executing gradlew ktfmtFormat:write before commit'

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.java" "*.kt" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
./gradlew ktfmtFormat --daemon

# store the last exit code in a variable
RESULT=$?

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit $RESULT
```

Share my currently available git hook scripts

**Comment by cortinico** [comment]
I'm looking into tackling this issue with #16

**Comment by GoldSubmarine** [comment]
I have updated the git hook script to format only the submitted files.

**Comment by cortinico** [comment]
> I have updated the git hook script to format only the submitted files.

So I suppose it's working fine now? :)

**Comment by GoldSubmarine** [comment]
Yes, I've already tested it. Thank you very much for your work.
