### ISSUE TITLE
Release a version 0.12.0 with ktfmt in Version 0.43.0

### ISSUE THREAD

**Issue by drademacher** [cortinico/ktfmt-gradle#124]
The master is already up-to-date when it comes to the version of ktfmt. It would be nice if there was also a release of the gradle plugin with the new version.

Even better would be to make the ktfmt version independent of ktfmt-gradle.

**Comment by cortinico** [comment]
Here you go 👍 https://github.com/cortinico/ktfmt-gradle/releases/tag/0.12.0
