### ISSUE TITLE
Tries to format generated kotlin files from sqldelight inside of the build folder.

### ISSUE THREAD

**Issue by abueide** [cortinico/ktfmt-gradle#158]
## ⚠️ Is your feature request related to a problem? Please describe

ktfmt is complaining about files generated by sqldelight when I run ktfmtCheck.

* What went wrong:
Execution failed for task ':shared:ktfmtCheckKmpCommonMain'.
> [ktfmt] Found 5 files that are not properly formatted:
  /home/andrea/programming/dialexa/accelerator-multiplatform/shared/build/generated/sqldelight/code/AcceleratorDb/migrations/USER_PROFILE.kt
  /home/andrea/programming/dialexa/accelerator-multiplatform/shared/build/generated/sqldelight/code/AcceleratorDb/migrations/VersionTable.kt
  /home/andrea/programming/dialexa/accelerator-multiplatform/shared/build/generated/sqldelight/code/AcceleratorDb/tables/VersionTableQueries.kt
  /home/andrea/programming/dialexa/accelerator-multiplatform/shared/build/generated/sqldelight/code/AcceleratorDb/tables/ProfileTableQueries.kt
  /home/andrea/programming/dialexa/accelerator-multiplatform/shared/build/generated/sqldelight/code/AcceleratorDb/com/dialexa/app/shared/AcceleratorDbImpl.kt

## 💡 Describe the solution you'd like

I'd like to be able to exclude generated sources from being checked/formatted.
## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
Thanks for the report, this is now fixed in #170
