### ISSUE TITLE
Question: How to apply to buildSrc?

### ISSUE THREAD

**Issue by msfjarvis** [cortinico/ktfmt-gradle#17]
I have code in a `buildSrc` subproject that I'd also like to format, are there any tricks around that would allow me to apply the plugin to the `buildSrc` directory?

**Comment by cortinico** [comment]
It's fairly easy. You can apply the plugin directly inside the `buildSrc/build.gradle` file.
I'm doing it here #18 

You can then run it with `./gradlew -p buildSrc ktfmtFormat` and so on
