### ISSUE TITLE
KtfmtBaseTask - rework FormattingOptionsBean to avoid lazy / null initializer

### ISSUE THREAD

**Issue by cloudshiftchris** [cortinico/ktfmt-gradle#184]
## ⚠️ Is your feature request related to a problem? Please describe
KtfmtBaseTask has an awkward null / lazy initialization of FormattingOptionsBean, making it unclear when (if) defaults or specific settings are provided.

## 💡 Describe the solution you'd like
Rework to be a first-class property with conventions as appropriate.

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by simonhauck** [comment]
I can reproduce this issue in our project. With 0.0.13 it works as expected :)

**Comment by cortinico** [comment]
Why you closed this?
