### ISSUE TITLE
Circular dependency between tasks caused by Spring Boot native build

### ISSUE THREAD

**Issue by lukas-krecan** [cortinico/ktfmt-gradle#191]
## 🐛 Describe the bug
When Spring Native build is used ("org.graalvm.buildtools.native") Gradle complains about circular dependency. 

## ⚠️ Current behavior
```
Circular dependency between the following tasks:
:classes
\--- :compileJava
     \--- :compileKotlin
          +--- :ktfmtCheckAot
          |    \--- :processAot
          |         +--- :classes (*)
          |         +--- :compileJava (*)
          |         +--- :compileKotlin (*)
          |         \--- :resolveMainClassName
          |              +--- :classes (*)
          |              +--- :compileJava (*)
          |              \--- :compileKotlin (*)
...
```

## ✅ Expected behavior
I expect it to pass

## 💣 Steps to reproduce
Clone https://github.com/lukas-krecan/ktfmt-native and run `./gradlew check`

The project was genberated by https://start.spring.io/ and ktfmt plugin added, nothing special.

**Comment by cortinico** [comment]
Thansk for the repro @lukas-krecan, this was really valuable in helping me fix this.
