### ISSUE TITLE
update ktfmt to 0.46 / release version using ktfmt 0.46

### ISSUE THREAD

**Issue by melo0187** [cortinico/ktfmt-gradle#196]
## ⚠️ Is your feature request related to a problem? Please describe
When a new version of ktfmt is released, some developers might have already updated the IntelliJ plugin, while others have not. This results in going back and forth between old and new version's formatting.

## 💡 Describe the solution you'd like
We want to use both the ktfmt IntelliJ plugin and the ktfmt-gradle plugin. Using the gradle plugin helps us avoid formatting back and forth between different versions, but ideally developers can use the IntelliJ plugin as well. When a new version of ktfmt is released, and the ktfmt-gradle plugin is updated in a timely manner, we can update the gradle task first, and all devs can update the IntelliJ plugin afterwards, without needing a coordinated IntelliJ plugin update in the team.

## 🤚 Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by melo0187** [comment]
There actually already is a merged renovate PR #194 
But the release for it was never issued. I assume this is because the GitHub actions workflow's Pre Merge Checks / gradle (windows-latest) job failed -> https://github.com/cortinico/ktfmt-gradle/actions/runs/6237186625/job/16930199227

**Comment by cortinico** [comment]
I'll have to publish a new version. Will try to do it as soon as I can

**Comment by cortinico** [comment]
Closed by https://github.com/cortinico/ktfmt-gradle/releases/tag/0.14.0
