### ISSUE TITLE
ktfmtFormat hangs out with context

### ISSUE THREAD

**Issue by rolintoucour** [cortinico/ktfmt-gradle#202]
## 🐛 Describe the bug
Introducing context receiver, the `build` task now hangs out on `ktfmtFormat`

## ⚠️ Current behavior
It hangs out

## ✅ Expected behavior
I should fail or success, at least finish

## 💣 Steps to reproduce
I introduced context receiver, in order to pass an Exposed transaction (I cannot share my private code).
I use the 0.14 release (with 0.13 there were an error).
I tested to apply the original facebook ktfmt (0.46) and it doesn't hang out.

**Comment by cortinico** [comment]
> I use the 0.14 release (with 0.13 there were an error).

Were there an error with 0.13 or not?

**Comment by simonhauck** [comment]
@rolintoucour Is this issue still relevant or can it be closed?

**Comment by simonhauck** [comment]
I will close this for now. If you encounter a similar problem with the current version, feel free to create a new issue :)
