### ISSUE TITLE
Upgrading to 0.15.0 results in build failure

### ISSUE THREAD

**Issue by sunkengxd** [cortinico/ktfmt-gradle#212]
## 🐛 Describe the bug
Plugin 0.15.0 fails gradle sync

## ⚠️ Current behavior
Upgrading to 0.15.0 throws the following error on gradle sync:
```Method 'org.jetbrains.kotlin.build.report.metrics.BuildTime[] org.jetbrains.kotlin.build.report.metrics.BuildTime.values()' must be InterfaceMethodref constant```

## 💣 Steps to reproduce
Bump version up to 0.15.0 and run sync

## 📱 Tech info
 - Kotlin: 1.9.10
 - Gradle: 8.0-8.4

**Comment by cortinico** [comment]
Do we have a reproducer of any sort?

**Comment by cortinico** [comment]
Also could you update to Kotlin 1.9.20 and verify if the issue persists?

**Comment by sunkengxd** [comment]
> Also could you update to Kotlin 1.9.20 and verify if the issue persists?

Works fine on Kotlin 1.9.20. Does this mean this is the minimum version from 0.15.0 on?

**Comment by cortinico** [comment]
Nope it is not, but it seems like there is a compatibility issue between ktfmt-gradle and another Gradle plugin you have in your build, that's why we need a reproducer

**Comment by simonhauck** [comment]
I have noticed that behavior as well. 
I tested it with a blank project, and there is still this issue. I thought it might even be an Kotlin problem?

**Comment by simonhauck** [comment]
Here is an example: https://github.com/simonhauck/kotlin-version-1.9.20-incompatibility

I reported a bug in YouTrack [here](https://youtrack.jetbrains.com/issue/KT-63022/Could-not-initialize-class-org.jetbrains.kotlin.gradle.report.ConfigureReporingKt-when-plugin-uses-Kotlin-1.9.20-and-project-is)

If you think it is just in this plugin, this would be great. But from my understanding this should not happen.

**Comment by agluszak** [comment]
I noticed that upgrading the `org.jetbrains.intellij` plugin from 1.15 to 1.16 and `org.jetbrains.kotlin:kotlin-gradle-plugin` from 1.9.10 to 1.9.20 seems to fix the issue

**Comment by agluszak** [comment]
I can confirm that ktfmt-gradle 0.14 works for me with `org.jetbrains.kotlin:kotlin-gradle-plugin` 1.9.20 and 0.15 does not

**Comment by cortinico** [comment]
I'm going to revert the Kotlin bump to 1.9.20 and put it on hold till JetBrains answers on https://youtrack.jetbrains.com/issue/KT-63022/Could-not-initialize-class-org.jetbrains.kotlin.gradle.report.ConfigureReporingKt-when-plugin-uses-Kotlin-1.9.20-and-project-is

**Comment by cortinico** [comment]
https://github.com/cortinico/ktfmt-gradle/releases/tag/0.15.1 is out which should address this isseu
