### ISSUE TITLE
Auto release upon ktfmt update

### ISSUE THREAD

**Issue by sergei-lapin** [cortinico/ktfmt-gradle#247]
## ⚠️ Is your feature request related to a problem? Please describe
When new version of upstream `ktfmt` is released there is a considerable delay until it is reflected in corresponding `ktfmt-gradle` release during which users can update IntelliJIDEA plugin and have misaligned behavior between it and, for example, git commit hooks.

## 💡 Describe the solution you'd like
On each commit to main branch check whether `ktfmt` is bumped and if so — trigger release action.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
> On each commit to main branch check whether ktfmt is bumped and if so — trigger release action.

Not easily possible as sometimes there are other changes on main.

**Comment by sergei-lapin** [comment]
But isn't it a benefit of trunk based development to always have an ability to cut off a new release?

**Comment by cortinico** [comment]
> But isn't it a benefit of trunk based development to always have an ability to cut off a new release?

Yes but I'd like to write release notes, bump stuff, etc. I'm happy to do a release after every ktfmt release or you can use the Gradle Worker to change ktfmt version independently from the release of this plugin: https://github.com/cortinico/ktfmt-gradle/pull/182

**Comment by cortinico** [comment]
Closing as https://github.com/cortinico/ktfmt-gradle/releases/tag/0.17.0 got released with the latest ktfmt version
