### ISSUE TITLE
Differences between ktfmt in Android Studio

### ISSUE THREAD

**Issue by gino-m** [cortinico/ktfmt-gradle#264]
## 🐛 Describe the bug
ktfmtFormat and ktfmtLint via Gradle created and expect a slightly different layout than the Android Studio ktfmt plugin.

## ⚠️ Current behavior
On comments and empty blocks, for example, we see the following:

<img width="1496" alt="image" src="https://github.com/cortinico/ktfmt-gradle/assets/228050/209fbad2-dd26-4fbe-a6b1-f06bc9e7f365">

(left = ktfmt-gradle, right = Android Studio plugin)

## ✅ Expected behavior

Both formatters produce the same result.

## 💣 Steps to reproduce

Copy and paste this example and run ktfmtFormat.

```kt
/**
 * Annotates view models to indicate that a single instance should be shared by all fragments in an
 * activity. Only one instance of such view models will be created per activity by
 * {@link ViewModelFactory#get(Fragment, Class)}.
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface SharedViewModel {

}
```

## 📷 Screenshots

See above.

@sufyanAbbasi FYI

**Comment by cortinico** [comment]
> ktfmtFormat and ktfmtLint via Gradle created and expect a slightly different layout than the Android Studio ktfmt plugin.

Which version of the two tools are you using?

**Comment by gino-m** [comment]
Apologies - we're using:

* com.ncorti.ktfmt.gradle version 0.17.0
* ktfmt Facebook plugin for Android Studio 1.1.0.47

**Comment by cortinico** [comment]
I've done some investigation, also using https://facebook.github.io/ktfmt/
The correct formatting is the one on the left, which you mentioned is the same result that ktfmt-gradle is producing.

I'll be closing this, but please open an issue on https://github.com/facebook/ktfmt as I believe this could be a bug on the IntelliJ Plugin
