### ISSUE TITLE
Use new version 0.51 of Ktfmt

### ISSUE THREAD

**Issue by simonhauck** [cortinico/ktfmt-gradle#302]
## ⚠️ Is your feature request related to a problem? Please describe

The IntelliJ Ktfmt plugin are now using different versions of Ktfmt. 
It would be great, if this plugin could use also the latest version

## 💡 Describe the solution you'd like

There are some breaking changes in the latest version. 
The dependency must be upgraded and the changes resolved

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Please do @simonhauck I see that the PR from renovate failed.
I do have some time tomorrow to review your other PR and can I also look into doing the bump if you don't have capacity
