### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by simonhauck** [cortinico/ktfmt-gradle#304]
## ⚠️ Is your feature request related to a problem? Please describe

Hey Cortinico,

could you create a new release?
Thanks in advance :)

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No, I cant :D

**Comment by cortinico** [comment]
I'll do it asap 👍

**Comment by simonhauck** [comment]
I know you are busy, but it would be really great if you could have a look :)
Since IntelliJ released the new ktfmt plugin, it is a bit annoying that the ktfmt gradle plugin and intellij plugin are no longer compatible.

If you want, I can already prepare the release with the version commit and update the changelog. Then you only have to trigger the release. You just have to tell me which version you want to have.

Additionally, if you are interested: I have developed a release plugin https://github.com/simonhauck/gradle-release-plugin that can automate the release process including updating the changelog. Then you would only need to run an action and the plugin could do the rest. Maybe that simplifies the work for you a bit :)

**Comment by xtrqt** [comment]
+1
