### ISSUE TITLE
[Chore] Remove usage of internal & deprecated methods in preparation for gradle 8.9

### ISSUE THREAD

**Issue by simonhauck** [cortinico/ktfmt-gradle#317]
## 🐛 Describe the bug

Some methods in the build.gradle.kts are deprecated and in gradle 8.9 also internal. This should be fixed.

## ⚠️ Current behavior

The build fails with gradle 8.9 and uses deprecated methods

## ✅ Expected behavior

Gradle 8.9 works and the files do not use deprecated methods

## 📱 Tech info
 - Device: 
 - OS: 
 - Library/App version:

**Comment by cortinico** [comment]
> Some methods in the build.gradle.kts are deprecated and in gradle 8.9 also internal. This should be fixed.

If you're referring to:

https://github.com/cortinico/ktfmt-gradle/blob/75c91b689895da29731d667e27859be21d72c62c/plugin-build/plugin/build.gradle.kts#L67-L72

Yup that can probably go now to unblock 8.9 migration

**Comment by simonhauck** [comment]
Yes, I would also remove the other deprecated calls. 

I think it is also possible now with testKit to simplify the dependency setup. I will see what is possible and create a PR

**Comment by cortinico** [comment]
Sure let's do it 👍
