### ISSUE TITLE
Task descriptions are incorrect

### ISSUE THREAD

**Issue by jessestricker** [cortinico/ktfmt-gradle#340]
The descriptions of `ktfmtFormat...` and `ktfmtCheck...` tasks are incorrect, I think they were just mixed up.

## Current behaviour

__Check Task:__
https://github.com/cortinico/ktfmt-gradle/blob/0d43625fa8988de6309b38fef7fdaead62c03978/plugin-build/plugin/src/main/java/com/ncorti/ktfmt/gradle/KtfmtPluginUtils.kt#L83 

__Format Task:__
https://github.com/cortinico/ktfmt-gradle/blob/0d43625fa8988de6309b38fef7fdaead62c03978/plugin-build/plugin/src/main/java/com/ncorti/ktfmt/gradle/KtfmtPluginUtils.kt#L110

**Comment by simonhauck** [comment]
You are probably right about that 👍
