### ISSUE TITLE
New release with ktfmt 0.53

### ISSUE THREAD

**Issue by simonhauck** [cortinico/ktfmt-gradle#373]
## ⚠️ Is your feature request related to a problem? Please describe

Ktfmt has a new release that fixes some bugs that prevent some people to update Kotlin.

https://github.com/facebook/ktfmt/releases/v0.53

@cortinico Should I create a new release?

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
> @cortinico Should I create a new release?

Please do 🙏
