### ISSUE TITLE
--include-only is not working 

### ISSUE THREAD

**Issue by akfpnd** [cortinico/ktfmt-gradle#69]
## 🐛 Describe the bug
Running gradle task `./gradlew ktfmtPrecommit --include-only=path/to/file.kt` is not including specified file to format.
Without `--include-only` everything works well

## ⚠️ Current behavior
command `./gradlew ktfmtPrecommit --include-only=path/to/file.kt` is not including specified file to format

## ✅ Expected behavior
command `./gradlew ktfmtPrecommit --include-only=path/to/file.kt` should include specified file to format

## 💣 Steps to reproduce
setup task in build.gradle file
```
tasks.register("ktfmtPrecommit", com.ncorti.ktfmt.gradle.tasks.KtfmtFormatTask) {
    source = project.fileTree(rootDir)
    include("**/*.kt")
}
```
do the change in any Kotlin file of the project then check the change by
`git diff --name-only`
then run command `./gradlew ktfmtPrecommit --include-only=path/to/file/from/git/diff/file.kt`
gradle task will ignore specified file 

I tried to use absolute path, tried to use `--include-only="path/to/file.kt"` nothing help

## 📷 Log
`[ktfmt] Skipping for: /absolute/path/to/file.kt because: Not included inside --include-only ` 
But is actually included!

## 📱 Tech info
Sytem: macOS 12.2.1
Android Studio: 2021.1.1 Patch 3
JVM version: 11
Gradle version: 7.1.3 (gradle-7.2-bin)
Library version: 0.8.0

**Comment by cortinico** [comment]
Thanks for the issue report @akfpnd 

> `[ktfmt] Skipping for: /absolute/path/to/file.kt because: Not included inside --include-only `
> But is actually included!

I'm not able to reproduce this behavior. I just tried on the `example` project with the snippet you posted. It works fine for me. Are you sure you're not invoking any other task or you don't have any formatter that are running from your IDE?

**Comment by akfpnd** [comment]
> Thanks for the issue report @akfpnd
> 
> > `[ktfmt] Skipping for: /absolute/path/to/file.kt because: Not included inside --include-only `
> > But is actually included!
> 
> I'm not able to reproduce this behavior. I just tried on the `example` project with the snippet you posted. It works fine for me. Are you sure you're not invoking any other task or you don't have any formatter that are running from your IDE?

Could you please create separate project from scratch with Android Studio version I mentioned and setup gradle task  in app `build.gradle `

```
tasks.register("ktfmtPrecommit", com.ncorti.ktfmt.gradle.tasks.KtfmtFormatTask) {
    source = project.fileTree(rootDir)
    include("**/*.kt")
}
```

use ` id 'com.ncorti.ktfmt.gradle' version '0.8.0'`

**Comment by cortinico** [comment]
I've added you to the repro here (it's private)
https://github.com/cortinico/reproducer-ktfmt-69/invitations

If you invoke
```
./gradlew ktfmtPrecommit --include-only=src/main/java/com/ncorti/kotlin/template/app/HelloWorld.kt
```
you'll see that the other file (MainActivity.kt) is not reformatted.

**Comment by cortinico** [comment]
@akfpnd where you able to test it?
