### ISSUE TITLE
Upgrade ktfmt to 0.39

### ISSUE THREAD

**Issue by Phlegethon90** [cortinico/ktfmt-gradle#74]
## ⚠️ Is your feature request related to a problem? Please describe

Versions in IntelliJ's plugin for ktfmt and this one are not equal, so that it results in different styling.

## 💡 Describe the solution you'd like
Use ktfmt version 0.39.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
This was addressed in https://github.com/cortinico/ktfmt-gradle/pull/73
Closing as it's merged. It will be released in the upcoming version 👍

**Comment by Phlegethon90** [comment]
Thank you!!!

**Comment by Phlegethon90** [comment]
> It will be released in the upcoming version 👍

When will you release the next version?

**Comment by cortinico** [comment]
I've released this yesterday
