### ISSUE TITLE
ktfmt* tasks are not configuration-cache compatible

### ISSUE THREAD

**Issue by sergei-lapin** [cortinico/ktfmt-gradle#81]
## 🐛 Describe the bug
ktfmt* tasks are not configuration-cache compatible because `KtfmtBaseTask.scope` is non-serializable 

## ⚠️ Current behavior
Build fails because of configuration cache issues

## ✅ Expected behavior
Build should succeed

## 💣 Steps to reproduce
Run `./gradlew :example:ktfmtFormat --configuration-cache`

**Comment by cortinico** [comment]
Thanks for the report. https://github.com/cortinico/ktfmt-gradle/pull/84 should fix this 👍

**Comment by sergei-lapin** [comment]
@cortinico when new version with these changes might be expected?
