### ISSUE TITLE
Lack of Android environment

### ISSUE THREAD

**Issue by GoldSubmarine** [cortinico/ktfmt-gradle#9]
I want to use this plugin in a springboot project, but failed because i dont have Android environment. I think this should be a universal plugin, why does it need Android environment?

## 📱 Tech info
 - Device: dell pc
 - OS: windows 10
 - Library/App version: 0.2.0

**Comment by cortinico** [comment]
> I think this should be a universal plugin, why does it need Android environment?

It actually is a universal plugin. AGP is set as a `compileOnly` dependency:
https://github.com/cortinico/ktfmt-gradle/blob/275e06bf73bab930b6a57c9e1d0d9cbdd209858e/plugin-build/plugin/build.gradle.kts#L25

Can you share your error message as this seems to be definitely a bug?

**Comment by GoldSubmarine** [comment]
I use the kotlin@1.4.30 but gradle is 6.7.0, upgrade the gradle solved the problem.

Thank you for your reply.
